; ============================================================
;  Classifier — PlatformIO Config
;  Board: Seeed Studio XIAO ESP32-S3
; ============================================================
;  Firmware: ADC + DSP + buffer PSRAM + TFLite (inferencia)
;
;    pio run -e classifier         → compilar
;    pio run -e classifier -t upload → flashear
; ============================================================

[env:classifier]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

board_build.arduino.memory_type = qio_opi

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

upload_speed    = 921600
monitor_speed   = 921600
monitor_filters = send_on_enter, colorize

; lib_deps =
;     adafruit/Adafruit PWM Servo Driver Library @ ^2.4.1
;     tensorflow/lite-micro
