[env]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

board_build.arduino.memory_type = qio_opi

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -Os
    -D MAC_OPT_ENABLE=1
    -Wa,--text-section-literals
    -Wa,--auto-litpools
    -mlongcalls

upload_speed    = 115200
monitor_speed   = 921600
lib_deps =
    tzapu/WiFiManager @ ^2.0.17

[env:classifier_svm]
build_flags =
    ${env.build_flags}
    -D MODEL_TYPE_SVM

[env:classifier_cnn]
build_flags =
    ${env.build_flags}
    -D MODEL_TYPE_CNN
    -D ESP_NN
lib_deps =
    ${env.lib_deps}
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0

[env:classifier_rf]
build_flags =
    ${env.build_flags}
    -D MODEL_TYPE_RF
