; ============================================================
;  Threshold Firmware — PlatformIO Config
;  Board: Seeed Studio XIAO ESP32-S3
; ============================================================
;  Firmware: Control Mioeléctrico por Umbral (Threshold)
;    - Core 1: Adquisición ADC (MCP3208 SPI) + DSP IIR @ 1kHz -> Ring Buffer
;    - Core 0: Evaluación de Umbral (MAV/RMS) -> ESP-NOW (Prótesis) + UDP/Serial
; ============================================================

[env:threshold]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

board_build.arduino.memory_type = qio_opi

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -Os
    -D MAC_OPT_ENABLE=1
    -Wa,--text-section-literals
    -Wa,--auto-litpools
    -mlongcalls

upload_speed    = 115200
monitor_speed   = 921600
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
