; ============================================================
;  MyoTensor — PlatformIO Config
;  Board: Seeed Studio XIAO ESP32-S3
; ============================================================

[env:seeed_xiao_esp32s3]
platform  = espressif32
board     = seeed_xiao_esp32s3
framework = arduino

; PSRAM OPI (Octal SPI) — el XIAO ESP32-S3 trae 8MB de PSRAM OPI
; Necesario para que ps_malloc() funcione correctamente
board_build.arduino.memory_type = qio_opi

build_flags =
    -D ARDUINO_USB_MODE=1        ; USB CDC nativo del ESP32-S3
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; Puerto serial disponible desde boot
    -D BOARD_HAS_PSRAM           ; Habilita soporte de PSRAM en el SDK

; Librerias
; lib_deps =
;     adafruit/Adafruit PWM Servo Driver Library @ ^2.4.1

upload_speed    = 921600
monitor_speed   = 921600
monitor_filters = send_on_enter, colorize
